CREATE TABLE IF NOT EXISTS events (
  EventId INT NOT NULL AUTO_INCREMENT,
  EventName VARCHAR(100) NOT NULL,
  EventDate DATE DEFAULT NULL,
  Location VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (EventId)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_uca1400_ai_ci;

