CREATE TABLE users (
  Id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci DEFAULT 'NULL',
  PRIMARY KEY (Id)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
COLLATE utf8mb4_uca1400_ai_ci
ROW_FORMAT = DYNAMIC;
